version: "3"
services:
    node:
        container_name: wvui-node
        build: .
        image: wikimedia/wvui
        volumes:
            - ./:/app
        working_dir: /app
    storybook:
        container_name: wvui-storybook
        build: .
        image: wikimedia/wvui
        volumes:
            - ./:/app
        working_dir: /app
        ports:
            - "3003:3003" # matches storybook port in npm start script
        command: npm start
